hf_model_id: "stable-diffusion-v1-5/stable-diffusion-v1-5"
hf_subfolder: "vae"
hf_gated: false
num_latent_channels: 4
downsample_factor: 8
num_slices_in_parallel: 4  # null means all slices in parallel
stochastic_encoder: false